name: Simple Start Up
on:
    push:
      branches: [main]
jobs:
  build:

    name: Build my virtual OS
  
    runs-on: Ubuntu-latest
  
    steps:
  
      - name: Checkout private repo remotely
        uses: actions/checkout@v2
        with:
          repository: explicitworkload/SFAHiddenRepository
          #path: explicitworkload/SFAHiddenRepository
          token: ${{ secrets.WHEREGOTTIMEAGAIN}} 

      - name: Show hidden files
        run: |
          ls